manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 5826b80374625d448cfbfc739dde4fda1e6f2681
      import: app/west.yml
  self:
    path: config
